SchoolRecognitionSystem/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Data.SqlClient;
using System.Web;
using System.Web.Mvc;
using SchoolRecognitionSystem.Models;

namespace SchoolRecognitionSystem.Controllers
{
    public class SettingsController : Controller
    {
        SchoolSubjectRecognitionContext ctx = new SchoolSubjectRecognitionContext();


       

        public ActionResult Index22()
        {
          
            

            return View();
        }





        // GET: Settings
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult CreateCustodian()
        {

            return View();

        }
        //public ActionResult CreateCustodian(cus)
        //{

        //    return View();

        //}
      
        public ActionResult CreateCategory(int page = 1, string sort = "cateeid", string sortDir = "ASC")
        {
            const int pageSize = 10;
            var totalRows = mobjMo.CountCategory();

            bool Dir = sortDir.Equals("desc", StringComparison.CurrentCultureIgnoreCase) ? true : false;

            var category = mobjMo.GetCategoryPage(page, pageSize, sort, Dir);
            var data = new PagedCustomerModel()
            {
                TotalRows = totalRows,
                PageSize = pageSize,
                Category = category
            };
            return View(data);
        }


        //public JsonResult GetFacility(string item)
        //{
        //    List<string> facilitys = new List<string>();
        //    switch (item)
        //    {
        //        case "1":
        //            facilitys.Add("Equipment Facility");
        //            facilitys.Add("Laboratory Facility");
                    
        //            break;
        //        case "2":
        //            facilitys.Add("Library Facility");
        //            facilitys.Add("Recreational Facility");
        //            facilitys.Add("Classroom Facility");
        //            facilitys.Add("Examination Facility");
        //            facilitys.Add("Assessment Facility");
        //            //add UK states here
        //            break;
               
        //    }
        //    return Json(facilitys);
        //}

        public List<FacilityCategory> LoadFacilitiesByRecognitionType(int categoryid)
        {

            var yy2 = ctx.FacilityCategories.Where(ci => ci.RecognitionID == categoryid);
                  
                 
            return yy2.ToList();

           
        }

        [HttpGet]
        public ActionResult CreateSubjectItems()
        {
            List<SelectListItem> recogs = new List<SelectListItem>();
            vmTypesettingsUser vmModel = new vmTypesettingsUser();

            List<SchoolRecognitionType> rect = ctx.SchoolRecognitionTypes.ToList();
            rect.ForEach(x =>
            {
                recogs.Add(new SelectListItem { Text = x.TypeofRecognition, Value = x.ID.ToString() });
            });
            vmModel.RecNames = recogs;
            return View(vmModel);

            //return View();

        }
        [HttpPost]
        public ActionResult GetFacility(string recid)
        {
            int reid;
            List<SelectListItem> facNames = new List<SelectListItem>();
            if (!string.IsNullOrEmpty(recid))
            {
                reid = Convert.ToInt32(recid);
                List<FacilityCategory> faccate =ctx.FacilityCategories.Where(x => x.RecognitionID == reid).ToList();
                faccate.ForEach(x =>
                {
                    facNames.Add(new SelectListItem { Text = x.TypeOfFacility, Value = x.ID.ToString() });
                });
            }
            return Json(facNames, JsonRequestBehavior.AllowGet);
        }

        public ActionResult activepage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateSubjectItems(vmTypesettingsUser set)
        {
            ViewBag.recognitiontypes = ctx.SchoolRecognitionTypes.Select(srt => new SelectListItem
            {
                Text = srt.TypeofRecognition,
                Value = srt.ID.ToString()
            });


            //ViewBag.PhoneAccessories =
            //    LoadFacilitiesByRecognitionType(set.FacilityTypeID).Select(s => new SelectListItem
            //    {
            //        Text = s.TypeOfFacility,
            //        Value = s.ID.ToString()
            //    }).ToList();



            //var facType = ctx.FacilityCategories.Select(p => new SelectListItem
            //{
            //    Text = p.TypeOfFacility,
            //    Value = p.ID.ToString()
            //});
            //ViewBag.FacilityTypes = facType;

            //var subjectx = ctx.Subjects.Where(ss => ss.HasItem == true).Select(s => new SelectListItem
            //{
            //    Text = s.LongName,
            //    Value = s.ID.ToString()
            //});
            //ViewBag.Subjects = subjectx;
            //if (ModelState.IsValid)
            //{
            //    Facility sett = new Facility();
            //    // sett.ItemDescription = set.ItemDescription;
            //    sett.isActive = set.isActive;

            //    ctx.Facilities.Add(sett);
            //    //ctx.SaveChanges();
            //    SchoolEquipConfig vv = new SchoolEquipConfig();
            //    vv.QuantityRequired = set.QuantityRequired;
            //    vv.SubjectID = set.SubjectID;
            //    ctx.SchoolEquipConfigs.Add(vv);
            //    ctx.SaveChanges();
            //    ModelState.Clear();
            //    TempData["Success"] = "subject is created";
            //}
            return View();

        }

        public ActionResult RenderSelectedItem(int selectedId = 0)
        {
            var model =LoadFacilitiesByRecognitionType(selectedId);
            ViewBag.selectedId = selectedId;
            return PartialView(model);
        }

        public JsonResult SubjectList()
        {
            
            var Subjects = (from s in ctx.Subjects select new { s.ID, s.LongName }).ToList();
           
            return Json(Subjects, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SummaryAsesmentFacility(/*int reccid, int facilityid,*/int page = 1, string sort = "catee", string sortDir = "ASC")
         {


            vmTypesettingsUser mobjMod = new vmTypesettingsUser();
            const int pageSize = 10;
            //var totalRows = mobjMod.CountLab();

            bool Dir = sortDir.Equals("desc", StringComparison.CurrentCultureIgnoreCase) ? true : false;

            var sumview = mobjMod.GetSummaryPage2(page, pageSize, sort, Dir);
            var yall = from p in sumview

                       select new Facility
                       {
                           ID = p.Facility.ID,
                           ItemDescription = p.Facility.ItemDescription,
                           //SumConfigID = p.ID,

                           FacilityCategoryID = p.Facility.FacilityCategoryID
                       };

            return PartialView("_SummaryAssessmentFacility", yall);

        }


        public ActionResult LaboratoryFacility(/*int reccid, int facilityid,*/int page = 1, string sort = "cateeid", string sortDir = "ASC")
        {


            vmTypesettingsUser mobjMod = new vmTypesettingsUser();
            const int pageSize = 10;
            //var totalRows = mobjMod.CountLab();

            bool Dir = sortDir.Equals("desc", StringComparison.CurrentCultureIgnoreCase) ? true : false;

            var Labview = mobjMod.GetLabPage(page, pageSize, sort, Dir);



            return PartialView("_LaboratoryFacility", Labview);

        }


       
        vmTypesettingsUser mobjMod = new vmTypesettingsUser();
        public ActionResult EquipmentFacility(/*int reccid, int facilityid*/ int page = 1, string sort = "cateeid", string sortDir = "ASC")
        {
           
            const int pageSize = 10;
            //var totalRows = mobjMod.CountLab();

            bool Dir = sortDir.Equals("desc", StringComparison.CurrentCultureIgnoreCase) ? true : false;

            var Equipview = mobjMod.GetEquipPage(page, pageSize, sort, Dir);
            //var data = new SchoolEquipView()
            //{
            //    //TotalRows = totalRows,
            //    //PageSize = pageSize,
            //    Equipment = Equipview
            //};


            return PartialView("_EquipmentFacility", Equipview);
        }


        








        public ActionResult ReloadGrid(int page = 1, string sort = "cateeid", string sortDir = "ASC")
        {
            vmTypesettingsUser mobjMod = new vmTypesettingsUser();
            const int pageSize = 10;
            //var totalRows = mobjMod.CountLab();

            bool Dir = sortDir.Equals("desc", StringComparison.CurrentCultureIgnoreCase) ? true : false;

            var Equipview = mobjMod.GetEquipPage(page, pageSize, sort, Dir);
            //var data = new SchoolEquipView()
            //{
            //    //TotalRows = totalRows,
            //    //PageSize = pageSize,
            //    Equipment = Equipview
            //};


            return PartialView("_EquipmentFacility", Equipview);
            

        }

        [HttpGet]
        public ActionResult CreateStaffCategory()
        {

            return View(new SchoolStaffCategory());
        }


        [HttpPost]
        public ActionResult CreateStaffCategory(SchoolStaffCategory ssf)
        {
            SchoolStaffCategory ss = new SchoolStaffCategory();
            ss.Category = ssf.Category;
            ss.isDefault = true;
            ctx.SchoolStaffCategories.Add(ss);
           // ctx.SaveChanges();
            TempData["Success"] = "subject is created";
            return View(ss);
        }

        //ModelServices mobjModel = new ModelServices();
       

SchoolRecognitionSystem/Views/Settings/CategoryGrid.cshtml
@model SchoolAndSubjectRecognition.Models.PagedCustomerModel
@{
    ViewBag.Title = "CategoryGrid";
    Layout = "~/Views/Shared/_SettingLayout.cshtml";
    WebGrid grid = new WebGrid(rowsPerPage: Model.PageSize);
    grid.Bind(Model.Category,
              autoSortAndPage: false,
              rowCount: Model.TotalRows
    );
}

<h2>School Category</h2>


<style type="text/css">
    #grid {
        clear: both;
        width: 80%;
        margin: 0px;
        border: 1px solid #c7c5c7;
    }

        #grid thead, #grid tfoot td {
            text-align: left;
            font-weight: bold;
            height: 35px;
            color: #000;
            background-color: #d2d0d2;
            border-bottom: 1px solid #e2e2e2;
        }

        #grid td {
            padding: 4px 6px 0px 4px;
            vertical-align: top;
            background-color: #f5f5f5;
            border-bottom: 1px solid #e2e2e2;
        }

    input {
        border: 1px solid #e2e2e2;
        background: #fff;
        color: #333;
        font-size: 1.2em;
        margin: 2px 0 2px 0px;
        padding: 2px;
        width: 170px;
    }
</style>
<script src="~/Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
<script type="text/javascript">

    $(".add").live("click", function () {

        var existrow = $('.save').length;
        if (existrow == 0) {
            var index = $("#grid tbody tr").length + 1;

            var Category = "Category_" + index;
          
            var Save = "Save_" + index;
            var Cancel = "Cancel_" + index;

            var tr = '<tr class="alternate-row"><td></td><td><span> <input id="' + Category + '" type="text" /></span></td>' +
              
                 '<td> <a href="#" id="' + Save + '" class="save">Save</a><a href="#" id="' + Cancel + '"  class="icancel">Cancel</a></td>' +
             '</tr>';

            $("#grid tbody").append(tr);
        }
        else {
            alert('First Save your previous record !!');
        }

    });

    $(".icancel").live("click", function () {
        var flag = confirm('Are you sure to cancel');
        if (flag) {
            $(this).parents("tr").remove();
        }

    });

    $(".save").live("click", function () {
        var id = $("#grid tbody tr").length;
        var CateName = $("#Category_" + id).val();
        //var Address = $("#Address_" + id).val();
        //var ContactNo = $("#ContactNo_" + id).val();

        if (id != "") {
            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("SaveRecord", "School")',
                data: { "catee": CateName },
                dataType: "json",
                beforeSend: function () { },
                success: function (data) {
                    if (data.result == true) {
                        $("#divmsg").html("Record has been saved successfully !!");
                        setTimeout(function () { window.location.replace("CategoryGrid"); }, 500);
                    }
                    else {
                        alert('There is some error');

                    }

                }

            });
        }
    });

    $(".edit").live("click", function () {
        var str = $(this).attr("id").split("_");
        id = str[1];

        var CateName = "#Category_" + id;
        var spanName = "#spanName_" + id;
        //var Address = "#Address_" + id;
        //var spanAddress = "#spanAddress_" + id;
        //var ContactNo = "#ContactNo_" + id;
        //var spanContactNo = "#spanContactNo_" + id;

        $(CateName).show();
        $(spanName).hide();
        //$(Address).show();
        //$(spanAddress).hide();
        //$(ContactNo).show();
        //$(spanContactNo).hide();

        $(this).hide();
        $("#Update_" + id).show();
        $("#Cancel_" + id).show();
    });

    $(".cancel").live("click", function () {
        var str = $(this).attr("id").split("_");
        id = str[1];

        var CateName = "#Category_" + id;
        var spanName = "#spanName_" + id;
        //var Address = "#Address_" + id;
        //var spanAddress = "#spanAddress_" + id;
        //var ContactNo = "#ContactNo_" + id;
        //var spanContactNo = "#spanContactNo_" + id;

        $(CateName).hide();
        $(spanName).show();
        //$(Address).hide();
        //$(spanAddress).show();
        //$(ContactNo).hide();
        //$(spanContactNo).show();

        $(this).hide();
        $("#Update_" + id).hide();

        $("#Edit_" + id).show();
    });

    $(".update").live("click", function () {
        var str = $(this).attr("id").split("_");
        id = str[1];

        var CateName = $("#Category_" + id).val();
        var spanName = $("#spanName_" + id).val();
        //var Address = $("#Address_" + id).val();
        //var spanAddress = $("#spanAddress_" + id).val();
        //var ContactNo = $("#ContactNo_" + id).val();
        //var spanContactNo = $("#spanContactNo_" + id).val();

        if (id != "") {
            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("UpdateRecord", "School")',
                data: { "id": id, "catee": CateName },
                dataType: "json",
                beforeSend: function () {//alert(id);
                },
                success: function (data) {

                    if (data.result == true) {
                        $("#Update_" + id).hide();
                        $("#Cancel_" + id).hide();
                        $("#Edit_" + id).show();

                        var CateName = "#Category_" + id;
                        var spanName = "#spanName_" + id;
                        //var Address = "#Address_" + id;
                        //var spanAddress = "#spanAddress_" + id;
                        //var ContactNo = "#ContactNo_" + id;
                        //var spanContactNo = "#spanContactNo_" + id;

                        $(CateName).hide();
                        $(spanName).show();
                        //$(Address).hide();
                        //$(spanAddress).show();
                        //$(ContactNo).hide();
                        //$(spanContactNo).show();

                        $(spanName).text($(CateName).val());
                        //$(spanAddress).text($(Address).val());
                        //$(spanContactNo).text($(ContactNo).val());
                    }
                    else {
                        alert('There is some error');
                    }
                }

            });
        }
    });

    $(".delete").live("click", function () {
        var str = $(this).attr("id").split("_");
        id = str[1];

        var flag = confirm('Are you sure to delete ??');
        if (id != "" && flag) {
            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("DeleteRecord", "School")',
                data: { "id": id },
                dataType: "json",
                beforeSend: function () { },
                success: function (data) {

                    if (data.result == true) {
                        $("#Update_" + id).parents("tr").remove();
                    }
                    else {
                        alert('There is some error');
                    }
                }

            });
        }
    });

</script>

<div id="divmsg" style="color: green; font-weight: bold"></div>
<a href="#" class="add">Add New Category</a>
<br />
<br />
@grid.GetHtml(
htmlAttributes: new { id = "grid" },
    fillEmptyRows: false,
    mode: WebGridPagerModes.All,
    firstText: "<< First",
    previousText: "< Prev",
    nextText: "Next >",
    lastText: "Last >>",
     columns: new[] {

        grid.Column("ID",
                    header: "ID", canSort: false),
        grid.Column(header: "Category",format: @<span> <span id="spanName_@item.ID">@item.Category</span> @Html.TextBox("Category_"+(int)item.ID,(string)item.Category,new{@style="display:none"})</span>),
        @*grid.Column(header: "Address",format: @<span> <span id="spanAddress_@item.CustID">@item.Address</span> @Html.TextBox("Address_"+(int)item.CustID,(string)item.Address,new{@style="display:none"})</span>),
        grid.Column(header: "Contact No",format: @<span> <span id="spanContactNo_@item.CustID">@item.ContactNo</span> @Html.TextBox("ContactNo_"+(int)item.CustID,(string)item.ContactNo,new{@style="display:none"})</span>),*@
        grid.Column(header: "Action",format:@<text> <a href="#" id="Edit_@item.ID" class="edit">Edit</a><a href="#" id="Update_@item.ID" style="display:none" class="update">Update</a><a href="#" id="Cancel_@item.ID" style="display:none" class="cancel">Cancel</a><a href="#" id="Delete_@item.ID" class="delete">Delete</a></text>)
})
     

SchoolRecognitionSystem/Views/Settings/CreateCategory.cshtml
@model SchoolRecognitionSystem.Models.PagedCustomerModel

@{
    ViewBag.Title = "CreateCategory";
    Layout = "~/Views/Shared/_SettingLayout.cshtml";
    WebGrid grid = new WebGrid(rowsPerPage: Model.PageSize);
    grid.Bind(Model.Category,
              autoSortAndPage: false,
              rowCount: Model.TotalRows
    );
}
<h2>School Category</h2>



<div id="divmsg" style="color: green; font-weight: bold"></div>

<br />
<br />
@grid.GetHtml(
htmlAttributes: new { id = "grid" },
    fillEmptyRows: false,
    mode: WebGridPagerModes.All,
    firstText: "<< First",
    previousText: "< Prev",
    nextText: "Next >",
    lastText: "Last >>",
     columns: new[] {
         grid.Column(null,null,canSort:false, format: @<input type="hidden" name="IDHidden" value="@item.ID" />),

        grid.Column(header: "Category",format: @<span> <span id="spanName_@item.ID">@item.Category</span> @Html.TextBox("Category_"+(int)item.ID,(string)item.Category,new{@style="display:none"})</span>),


grid.Column(header: "Action",format:@<text> <a href="#" id="Edit_@item.ID" class="edit">Edit &nbsp;</a><a href="#" id="Update_@item.ID" style="display:none" class="update">Update &nbsp;</a><a href="#" id="Cancel_@item.ID" style="display:none" class="cancel">Cancel &nbsp;</a><a href="#" id="Delete_@item.ID" class="delete">Delete</a></text>)

})
<br />

<span class="glyphicon glyphicon-plus-sign"></span>
<a href="#" class="add">Add</a>




<style type="text/css">
    #grid {
        clear: both;
        width: 80%;
        margin: 0px;
        border: 1px solid #c7c5c7;
    }

        #grid thead, #grid tfoot td {
            text-align: left;
            font-weight: bold;
            height: 35px;
            color: #000;
            background-color: #d2d0d2;
            border-bottom: 1px solid #e2e2e2;
        }

        #grid td {
            padding: 4px 6px 0px 4px;
            vertical-align: top;
            background-color: #f5f5f5;
            border-bottom: 1px solid #e2e2e2;
        }

    input {
        border: 1px solid #e2e2e2;
        background: #fff;
        color: #333;
        font-size: 1.2em;
        margin: 2px 0 2px 0px;
        padding: 2px;
        width: 170px;
    }
</style>
<script src="~/Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
<script type="text/javascript">

    $(".add").live("click", function () {

        var existrow = $('.save').length;
        
        if (existrow == 0) {
            var index = $("#grid tbody tr").length + 1;
            
            var Category = "Category_" + index;

            var Save = "Save_" + index;
            var Cancel = "Cancel_" + index;

            var tr = '<tr class="alternate-row"><td></td><td><span><input id="' + Category + '" type="text" class="ty" /></span></td>' +

                 '<td> <a href="#" id="' + Save + '" class="save">Save&nbsp;&nbsp;</a><a href="#" id="' + Cancel + '"  class="icancel">Cancel</a></td>' +
             '</tr>';

            $("#grid tbody").append(tr);
        }
        else {
            
            alert('First Save your previous record !!');
        }

    });

    $(".icancel").live("click", function () {
        var flag = confirm('Are you sure to cancel');
       
        if (flag) {
            $(this).parents("tr").remove();
        }

    });

    $(".save").live("click", function () {
        var id = $("#grid tbody tr").length;
        var CateName = $("#Category_" + id).val();
        var index = $("#grid tbody tr").length + 1;
      
        if ($('.ty').val() === '') {
            alert('Text box can not be left blank');
            return false;
        }

        if (id != "") {

            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("SaveRecordCat", "Settings")',
                data: { "catee": CateName },
                dataType: "json",
                beforeSend: function () { },
                success: function (data) {
                    if (data.result == true) {

                        alert('Record has been saved successfully !!');

                        setTimeout(function () { window.location.replace("CreateCategory"); });
                    }
                    else {
                        alert('Record already exist');

                    }

                }

            });
        }
    });

    $(".edit").live("click", function () {
        var str = $(this).attr("id").split("_");
        id = str[1];
        
        var CateName = "#Category_" + id;
        var spanName = "#spanName_" + id;

        $(CateName).show();
        $(spanName).hide();

        $(this).hide();
        $("#Update_" + id).show();
        $("#Cancel_" + id).show();
    });

    $(".cancel").live("click", function () {
        var str = $(this).attr("id").split("_");
        
        id = str[1];

        var CateName = "#Category_" + id;
        var spanName = "#spanName_" + id;


        $(CateName).hide();
        $(spanName).show();


        $(this).hide();
        $("#Update_" + id).hide();

        $("#Edit_" + id).show();
    });

    $(".update").live("click", function () {
        var str = $(this).attr("id").split("_");
        id = str[1];

        var CateName = $("#Category_" + id).val();
        var spanName = $("#spanName_" + id).val();


        if (id != "") {
            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("UpdateRecordSchCate", "Settings")',
                data: { "id": id, "catee": CateName },
                dataType: "json",
                beforeSend: function () {
                },
                success: function (data) {

                    if (data.result == true) {
                        $("#Update_" + id).hide();
                        $("#Cancel_" + id).hide();
                        $("#Edit_" + id).show();

                        var CateName = "#Category_" + id;
                        var spanName = "#spanName_" + id;


                        $(CateName).hide();
                        $(spanName).show();


                        $(spanName).text($(CateName).val());

                    }
                    else {
                        alert('There is some error');
                    }
                }

            });
        }
    });

    $(".delete").live("click", function () {
        var str = $(this).attr("id").split("_");
        id = str[1];

        var flag = confirm('Are you sure to delete ??');
        if (id != "" && flag) {
            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("DeleteRecordCategory", "Settings")',
                data: { "id": id },
                dataType: "json",
                beforeSend: function () { },
                success: function (data) {

                    if (data.result == true) {
                        $("#Update_" + id).parents("tr").remove();
                    }
                    else {
                        alert('There is some error');
                    }
                }

            });
        }
    });

</script>

SchoolRecognitionSystem/Views/Settings/CreateStaffCategory.cshtml
@model SchoolRecognitionSystem.Models.SchoolStaffCategory

@{
    ViewBag.Title = "CreateStaffCategory";
    Layout = "~/Views/Shared/_SettingLayout.cshtml";
}

<h2>Create Staff Category</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p class="label-success">@TempData["ItemExist"]</p>
        <p class="label-success">@TempData["Success"]</p>
        @*<h4>SchoolStaffCategory</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
         
        <div class="form-group">
            @Html.LabelFor(model => model.Category, "Staff category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isDefault, "is default", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.isDefault)
                    @Html.ValidationMessageFor(model => model.isDefault, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SchoolRecognitionSystem/Views/Settings/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Settinglayout.cshtml";
}

<h2>Index</h2>

SchoolRecognitionSystem/Views/Settings/RenderSelectedItem.cshtml
@model IEnumerable<SchoolRecognitionSystem.Models.FacilityCategory>
@foreach (var pc in Model)
{
    if (ViewBag.selectedId == 0)
    {
        <option value="@pc.ID">@pc.TypeOfFacility</option>
    }
    else
    {
        if ((int)ViewBag.selectedId == @pc.ID)
        {
            <option value="@pc.ID" selected="selected">@pc.TypeOfFacility</option>
        }
        else
        {
            <option value="@pc.ID">@pc.TypeOfFacility</option>
        }
    }
}

SchoolRecognitionSystem/Views/Settings/SetCouncilSubject.cshtml
@model SchoolRecognitionSystem.Models.Subject

@{
    ViewBag.Title = "SetCouncilSubject";
    Layout = "~/Views/Shared/_SettingLayout.cshtml";
}

<h2>Set Council Subject</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Subject</h4>*@
        <p class="label-success">@TempData["ItemExist"]</p>
        <p class="label-success">@TempData["Success"]</p> 
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubjectCode, "subject code", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubjectCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubjectCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortName, "short name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LongName, "long name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LongName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LongName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HasItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBox("HasItem", "has school item")
                    @Html.ValidationMessageFor(model => model.HasItem, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>