SchoolRecognitionSystem/Controllers/AutoCentreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolRecognitionSystem.Classes;

namespace SchoolRecognitionSystem.Controllers
{
    public class AutoCentreController : Controller
    {
        // GET: AutoCentre
        public ActionResult Index(int page=1)
        {
            //var userId = int.Parse(Session.GetDataFromSession<string>("UserID").ToString());
            var allSchools = clsContent.GetSchoolsApproved(page, 20);
            TempData["Message"] = Session.GetDataFromSession<string>("UserFullName");
            ViewBag.ApprovedSchools = "active";
            return View(allSchools);
        }
        private void GetGenerateCentreFormData()
        {
            IEnumerable<SelectListItem> examType = new SelectList(clsContent.GetExamType(), "ID", "ExamType");

            IEnumerable<SelectListItem> objSchCategory = new SelectList(clsContent.GetSchoolCategory(), "ID", "Category");
            IEnumerable<SelectListItem> objStates = new SelectList(clsContent.GetStates(), "StateCode", "StateName");
            IEnumerable<SelectListItem> objSchools = new SelectList(clsContent.GetSchoolsApproved(), "ID", "SchoolName");
            ViewBag.ExamType = examType;
            ViewBag.CategoryList = objSchCategory;
            ViewBag.StatesList = objStates;
            ViewBag.Schools = objSchools;
            //ViewBag.CouncilSubjectList = objCouncilSubject;
        }
        public ActionResult Create()
        {
            return View();
        }//GenerateCentre
        [HttpGet]
        public ActionResult GenerateCentre()
        {
           // var examtype = clsContent.GetExamType();
           // var getSchool = clsContent.GetSchoolByID(sddc);
            GetGenerateCentreFormData();
            ViewBag.GenerateCentre = "active";
            return View();
        }
    }
}

SchoolRecognitionSystem/Views/AutoCentre/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutUserHome.cshtml";
}

<h2>Create</h2>

SchoolRecognitionSystem/Views/AutoCentre/GenerateCentre.cshtml
@model  SchoolRecognitionSystem.Models.CentreTableModel
@{
    ViewBag.Title = "Generate Centre";
    Layout = "~/Views/Shared/_LayoutAutoCentreHome.cshtml";
}

<link href="~/Content/dropdownliststyle.css" rel="stylesheet" />
<ol class="breadcrumb">
    <li><i class="glyphicon glyphicon-plane"></i></li>
    
</ol>
@*<script src="~/Scripts/141jquery.js"></script>*@
@*<h2>FacilityTabbing</h2>*@
<div class="row">
    <section class="col-lg-11 col-md-11 col-sm-11 col-xs-11 mycustom-tab-container">
        <aside class="col-lg-2 col-md-2 col-sm-2 col-xs-2 mycustom-tab-menu">
            @Html.Partial("_AutoCentrePartial");
        </aside>
        <article class="col-lg-10 col-md-10 col-sm-10 col-xs-10 mycustom-tab">
            <section class="row">
                <article class="col-lg-9 col-md-9 col-sm-10 col-xs-10">

                    @if (TempData["DataSavedSuccessfully"] != null)
                    {
                        <div id="result" class="alert alert-success">
                            @TempData["DataSavedSuccessfully"]
                        </div>
                    }


                    <!-- flight section -->

                    <span id="messagesuccess"></span>
                    @*@if (Session["SchoolID"] != null)
            {*@
                    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data", @id = "registerFormId" }))
                    {
                        @Html.AntiForgeryToken()
                        HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @*<p style="color:green">@ViewBag.Success</p>*@

                            <div class="form-group">
                                @Html.LabelFor(model => model.ExamType, "Exam Type", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.ExamType, ViewBag.ExamType as SelectList, "(select ExamType)", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ExamType, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.StateId, "State", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.StateId, ViewBag.StatesList as SelectList, "(select State)", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.SchoolId, "Local Govenment Area", htmlAttributes: new {@class = "control-label col-md-3"})
                                <div class="col-md-9">
                                    <select id="LgaID" name="LgaID" class="form-control">
                                        <option value="0" selected="selected">(select LGA)</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ID, "Centre name", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.ID, ViewBag.Schools as SelectList, "(select School)", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                          
                            <div class="form-group">
                        @Html.LabelFor(model => model.CenterEmailAddress, "Center Email Address", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CenterEmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CenterEmailAddress, "", new { @class = "text-danger" })
                        </div>
                    </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.CategoryID, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.CategoryID, ViewBag.CategoryList as SelectList, "(select ExamType)", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            @*<div class="form-group">
                        @Html.LabelFor(model => model.CategoryID, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model=>model.CategoryID, ViewBag.CategoryList, "(select Category)", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                        </div>
                    </div>*@


                            <input type="hidden" id="teacher-added" name="teacherAdded" value="0" />


                            <input type="hidden" id="ID" name="ID" value="0" />
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Add" class="btn btn-primary" />



                                </div>
                            </div>
                        </div>
                    }

                </article>


            </section>
        </article>
    </section>
</div>


@section scripts{
    @*@Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/custom-validator")*@
    @*<script src="~/Scripts/190jquery.min.js"></script>*@
    <script src="~/Scripts/jquery.sumoselect.js"></script>
   

    <script type="text/javascript">

        $(document).ready(function () {

            $('#ID').select2();

            $("#StateId").on("change", function () {
                var id = $(this).val();
                var baseUrl = '@Url.Content("~/")';
                var url = baseUrl + "api/recog/GetLgas";
                var markup = "<option value='0' selected='selected'>--select LGA--</option>";
                $("#LgaID").html(markup).show();
                $.get(url, { StateID: id }, function (data) {
                    if (data != null) {
                        for (var i = 0; i < data.length; i++) {
                            markup += "<option value='" + data[i].Id + "'>" + data[i].Name + "</option>";
                        }

                        $("#LgaID").html(markup).show();
                    }
                });
            });
        });
    </script>
}

SchoolRecognitionSystem/Views/AutoCentre/Index.cshtml
@model PagedList.IPagedList<SchoolRecognitionSystem.Models.SchoolProfileViewModel1>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Welcome";
    Layout = "~/Views/Shared/_LayoutUserHome.cshtml";
}
<div class="container-fluid">
    <h2>Schools</h2>
    @if (Model.Count > 0)
    {
        <section class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Category</th>
                        <th>Name</th>
                        <th>Location</th>
                        <th>LGA</th>
                        <th>State</th>
                        <th>Created By</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var sn = (Model.PageNumber - 1) * Model.PageSize + 1;
                    }
                    @foreach (var item in Model)
                {
                        <tr>
                            <th>@sn</th>
                            <td>@item.Category</td>
                            <td>@item.SchoolName</td>
                            <td>@item.SchoolLocation</td>
                            <td>@item.Name</td>
                            <td>@item.StateName</td>
                            <td>@item.EmailAddress</td>
                            <td>
                                <a class="btn btn-success btn-sm" href="@Url.Action("GenerateCentre","AutoCentre", new {sddc=item.ID})">Edit</a>
                                <a class="btn btn-primary btn-sm" href="@Url.Action("School","SchoolsEdit", new {sddc=item.ID})">Details</a>

                            </td>
                        </tr>
                        sn++;
                    }
                </tbody>
            </table>
            <div id='Paging' style="text-align: center">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

            </div>
        </section>
                        }
</div>