SchoolRecognitionSystem/Models/ClassRoom.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRecognitionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoom
    {
        public int ID { get; set; }
        public Nullable<long> SchoolID { get; set; }
        public Nullable<int> NumberofClassroomInUse { get; set; }
        public Nullable<int> CapacityOfEachClassRoom { get; set; }
        public string DeskChairsAdequate { get; set; }
    
        public virtual SchoolProfile SchoolProfile { get; set; }
    }
}

SchoolRecognitionSystem/Models/Staff.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRecognitionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public Nullable<int> RankID { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<int> OfficeID { get; set; }
    
        public virtual Title Title { get; set; }
    }
}

SchoolRecognitionSystem/Controllers/EditSchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolRecognitionSystem.Classes;
using SchoolRecognitionSystem.Models;

namespace SchoolRecognitionSystem.Controllers
{
    public class EditSchoolController : Controller
    {
        // GET: EditSchool
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EditSchool(int sdc)
        {
            var getSchool = clsContent.GetSchoolByID(sdc);
            var objYears = new SelectList(clsContent.GetYears(), "yearName", "yearName", getSchool.YearEstablished);
            var objSchCategory = new SelectList(clsContent.GetSchoolCategory(), "ID", "Category", getSchool.CategoryID);
           // var objStates = new SelectList(clsContent.GetStates(), "Id", "StateName", getSchool.StateID);
            ViewBag.AvailableYears = objYears;
            ViewBag.CategoryList = objSchCategory;
            ViewBag.State = clsContent.GetStatesById(getSchool.StateID);
            ViewBag.Lgas = new SelectList(clsContent.GetLgas(getSchool.StateID), "ID", "Name", getSchool.LgaID);
            ViewBag.EditSchool = "active";
            return View(getSchool);
        }
        [HttpPost]
        public ActionResult EditSchool(SchoolProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var getSchool = clsContent.GetSchoolByID(model.ID);
                var objYears = new SelectList(clsContent.GetYears(), "yearName", "yearName", getSchool.YearEstablished);
                var objSchCategory = new SelectList(clsContent.GetSchoolCategory(), "ID", "Category",
                    getSchool.CategoryID);
                // var objStates = new SelectList(clsContent.GetStates(), "Id", "StateName", getSchool.StateID);
                ViewBag.AvailableYears = objYears;
                ViewBag.CategoryList = objSchCategory;
                ViewBag.State = clsContent.GetStatesById(getSchool.StateID);
                ViewBag.Lgas = new SelectList(clsContent.GetLgas(getSchool.StateID), "ID", "Name", getSchool.LgaID);
                return RedirectToAction("Details", new {schoolid = model.ID });
            }
            return View(model);
        }

        public ActionResult Details()
        {
            return View();
        }
        public ActionResult EditSubject()
        {
            return View();
        }
        public ActionResult EditTextbook()
        {
            return View();
        }
        public ActionResult EditClass()
        {
            return View();
        }
        public ActionResult EditStaff()
        {
            return View();
        }
        public ActionResult EditEquipment()
        {
            return View();
        }
        public ActionResult EditReagent()
        {
            return View();
        }
        public ActionResult EditLab()
        {
            return View();
        }
        public ActionResult EditLibrary()
        {
            return View();
        }
        public ActionResult EditExam()
        {
            return View();
        }
        public ActionResult EditRecreational()
        {
            return View();
        }

    }
}

SchoolRecognitionSystem/Controllers/SchoolsController.cs
using PagedList;
using SchoolRecognitionSystem.Classes;
using SchoolRecognitionSystem.Models;
using System;
using System.Collections.Generic;
using System.Collections;
using System.Configuration;
using System.Linq;
using System.Data.Entity;
using System.Data;
using System.DirectoryServices.ActiveDirectory;
using System.Globalization;
using System.Runtime.InteropServices.ComTypes;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using System.IO;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Net.WebSockets;
using System.Transactions;
using System.Xml.Linq;
using SchoolRecognitionSystem.Infrastructure;
using SchoolRecognitionSystem.Pdf;
using SchoolRecognitionSystem.Report;
using WebGrease.Css.Extensions;
using RemoveNullableClass = SchoolRecognitionSystem.Classes.RemoveNullableClass;

namespace SchoolRecognitionSystem.Controllers
{
    //[AuthorizeAccess(Roles = "admin,super_admin")]
    [SchoolRecognitionAuthorized]
    public class SchoolsController : BaseController
    {
        private SchoolSubjectRecognitionContext ctx = new SchoolSubjectRecognitionContext();

        public ActionResult ReadCentres()
        {
            var centres = System.IO.File.ReadAllLines(Server.MapPath("~/WAEC/CentreFile.txt"));
            var formattedCentres = new List<SchoolCentre>();
            foreach (var centre in centres)
            {
                var real = centre.Substring(2);
                var centreNumber = real.Substring(0, 7);
                var centreName = real.Substring(8);
                formattedCentres.Add(new SchoolCentre {CentreName = centreName, CentreNumber = centreNumber});
                clsContent.InsertSchoolCentre(centreName, centreNumber);
                //if existing dont save else save

            }

            ViewBag.Centres = centres;
            return View(formattedCentres);
        }


        private void GetSchoolSubjectItems(int? subjectid)
        {
            var schoo = ConstantsService.GetCookie(ConstantsService.CookieSchoolIdKey).Value;
            var schoolid = long.Parse(schoo);
            var schy = clsContent.GetSchoolSubjectItems(schoolid).Select(s => new SelectListItem
            {
                Text = s.LongName,
                Value = s.ID.ToString(),
                Selected = (s.ID == subjectid)
            });
            ViewBag.SchoolSubjectList = schy;


        }


        private void GetSubjectItemsFormData(int? subjectid)
        {
            var schy = clsContent.GetCouncilSubjectsItems().Select(s => new SelectListItem
            {
                Text = s.LongName,
                Value = s.ID.ToString(),
                Selected = (s.ID == subjectid)
            });
            ViewBag.SchoolSubjectList = schy;

        }

        private void GetClassFormData()
        {
            //GetStudentClassRecord

            IEnumerable<SelectListItem> classes = new SelectList(clsContent.GetClass(), "ID", "ClassName");

            ViewBag.Classes = classes;

        }





        private void GetRecognitionTypeFormData()
        {
            IEnumerable<SelectListItem> TypeRec = new SelectList(clsContent.GetSchoolRecogntion(), "ID",
                "TypeofRecognition");

            ViewBag.TypeofRecognition = TypeRec;
        }

        private SchoolSubjectViewModel GetFacilityFormData()
        {
            return new SchoolSubjectViewModel
            {
                AvailableSubjects = clsContent.GetCouncilSubjects(),
                RequestedSubjects = new List<SubjectModel>()
            };
        }

        private void GetSchoolStaffFormData()
        {
            //  IEnumerable<SelectListItem> titles = new SelectList(clsContent.GetTitle(), "TitleID", "TitleName");
            //  IEnumerable<SelectListItem> staffcatgory = new SelectList(clsContent.GetSchoolStaffCategory(), "DegreeID", "Category");
            //  IEnumerable<SelectListItem> Degrees = new SelectList(clsContent.GetSchoolStaffCategory(), "CategoryID", "Category");
            //IEnumerable<SelectListItem> objSchCategory = new SelectList(clsContent.GetCourse(), "ID", "Category");


            //return new SchoolSubjectViewModel { AvailableSubjects = clsContent.GetCouncilSubjects(), RequestedSubjects = new List<Subject>() };
        }

        private void GetSchoolFormData()
        {
            IEnumerable<SelectListItem> objYears = new SelectList(clsContent.GetYears(), "yearName", "yearName");
            IEnumerable<SelectListItem> objSchCategory = new SelectList(clsContent.GetSchoolCategory(), "ID", "Category");

            IEnumerable<SelectListItem> objStates = new SelectList(clsContent.GetStates(), "StateCode", "StateName");

            //IEnumerable<SelectListItem> objCouncilSubject = new SelectList(clsContent.GetCouncilSubjects(), "ID", "LongName");



            ViewBag.AvailableYears = objYears;
            ViewBag.CategoryList = objSchCategory;
            ViewBag.StatesList = objStates;
            //ViewBag.CouncilSubjectList = objCouncilSubject;
        }

        public ActionResult SendEmail(Gmail gmail)
        {
            var mess = new MailMessage("paogbekhilu@waec.org.ng", gmail.To);
            mess.Body = gmail.Body;
            mess.Subject = gmail.Subject;
            mess.IsBodyHtml = false;
            var client = new SmtpClient();
            client.Port = 25;
            client.EnableSsl = true;
            client.Host = "mail.waec.org.ng";
            var net = new NetworkCredential("paogbekhilu@waec.org.ng", "welcome");
            client.UseDefaultCredentials = true;
            client.Credentials = net;
            client.Send(mess);
            ViewBag.Email = "Email has been sent successfully";
            return View();
        }

        private void GetStaffFormData()
        {
            IEnumerable<SelectListItem> objYears = new SelectList(clsContent.GetYears(), "yearName", "yearName");
            IEnumerable<SelectListItem> objSchCategory = new SelectList(clsContent.GetSchoolCategory(), "ID", "Category");

            IEnumerable<SelectListItem> objStates = new SelectList(clsContent.GetStates(), "StateCode", "StateName");
            //IEnumerable<SelectListItem> objCouncilSubject = new SelectList(clsContent.GetCouncilSubjects(), "ID", "LongName");



            ViewBag.AvailableYears = objYears;
            ViewBag.CategoryList = objSchCategory;
            ViewBag.StatesList = objStates;
            //ViewBag.CouncilSubjectList = objCouncilSubject;
        }

        public ActionResult DefineOption()
        {
            ViewBag.DefineOptions = "active";
            return View();

        }

        public ActionResult ActionPerform()
        {
            ViewBag.ActionPerform = "active";
            return View();

        }


        [HttpGet]
        public ActionResult SubjectInfo(int subject_id, long schoolid)
        {

            TempData["Message"] = CurrentUser.EmailAddress;

            var AschoolSubjectInfo = clsContent.GetAASchoolSubjectApprovedBySchoolID(subject_id, schoolid);


            return Json(new
            {
                status = true,
                hasitem = AschoolSubjectInfo.HasItem,
                adequateEquipment = AschoolSubjectInfo.AdequateEquipment,
                adequateReagent = AschoolSubjectInfo.AdequateReagent,
                adequateLaboratory = AschoolSubjectInfo.AdequateLaboratory,
                adequateQualifiedStaff = AschoolSubjectInfo.QualifiedStaff,
                adequateExam = AschoolSubjectInfo.ExaminationMalpractice

            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SubjectDerecogntion(long sdc)
        {

            TempData["Message"] = CurrentUser.EmailAddress;

            var school = clsContent.GetSchoolById(sdc);
            var reasonForDerecogition = clsContent.ReasonsForDerecognition();
            ViewBag.SchoolIdd = sdc;
            ViewBag.ReasonForDerecogition = reasonForDerecogition;
            var subjectmodel = clsContent.GetSchoolSubjectApprovedBySchoolId(sdc);
            ViewBag.SideSubjects = clsContent.GetSchoolSubjectApprovedBySchoolId(sdc);
            TempData["DisplaySchoolName"] = school.SchoolName;
            ViewBag.UpdateSubject = "active";
            ViewBag.SchoolId = sdc;
            ViewBag.Subjectmodel = new SelectList(clsContent.GetSchoolSubjectApprovedBySchoolId(sdc), "SubjectID",
                "LongName");
            // var subjectmodel = new SelectList(clsContent.GetSchoolSubjectApprovedBySchoolId(sdc), "SubjectID", "LongName");

            return View(subjectmodel);
        }

        [HttpPost]
        public ActionResult SubjectDerecogntion(SchoolSubjectViewModel model)
        {
            //TempData["Message"] = CurrentUser.EmailAddress;

            //var school = clsContent.GetSchoolById(model.SchoolID);
            //var reasonForDerecogition = clsContent.ReasonsForDerecognition();
            //ViewBag.ReasonForDerecogition = reasonForDerecogition;
            var subjectmodel = clsContent.GetSchoolSubjectApprovedBySchoolId(model.SchoolID);
            //TempData["DisplaySchoolName"] = school.SchoolName;
            //ViewBag.UpdateSubject = "active";
            //ViewBag.SchoolId = model.SchoolID;
            //ViewBag.Subjectmodel = new SelectList(clsContent.GetSchoolSubjectApprovedBySchoolId(model.SchoolID), "SubjectID", "LongName");
            // var subjectmodel = new SelectList(clsContent.GetSchoolSubjectApprovedBySchoolId(sdc), "SubjectID", "LongName");

            return View(subjectmodel);
        }

        public ActionResult GetSchoolByValidCentre(string centreNumber)
        {
            if (!string.IsNullOrEmpty(centreNumber))
            {
                var returnValue = new SchoolProfileViewModel1();
                try
                {

                    returnValue = clsContent.GetSchoolByValidCentre(centreNumber);

                }
                catch

SchoolRecognitionSystem/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolRecognitionSystem.Models;

namespace SchoolRecognitionSystem.Controllers
{
    public class SubjectController : Controller
    {
        SchoolSubjectRecognitionContext ctx = new SchoolSubjectRecognitionContext();
        // GET: Subject
        public ActionResult Index()
        {
            return View();
        }
       

       

      
        [HttpGet]
        public ActionResult CreateCouncilSubject()
        {
          
            return View();

        }
        [HttpPost]
        public ActionResult CreateCouncilSubject(Subject suj)
        {

            return View();

        }

        //[HttpGet]
        //public ActionResult CreateSubjectItems()
        //{
        //    var facType = ctx.FacilityTypes.Select(p => new SelectListItem
        //    {
        //        Text = p.TypeOfFacility,
        //        Value = p.ID.ToString()
        //    });
        //    ViewBag.FacilityTypes = facType;

        //    var subjectx = ctx.Subjects.Select(s => new SelectListItem
        //    {
        //        Text = s.LongName,
        //        Value = s.ID.ToString()
        //    });
        //    ViewBag.Subjects = subjectx;
        //    return View(new vmTypesettingsUser());

        //}
        //[HttpPost]
        //public ActionResult CreateSubjectItems(vmTypesettingsUser set)
        //{
        //    return View();

        //}
    }
}

SchoolRecognitionSystem/Views/Schools/CreateCategory.cshtml
@model SchoolRecognitionSystem.Models.PagedCustomerModel

@{
    ViewBag.Title = "CreateCategory";
    Layout = "~/Views/Shared/_SettingLayout.cshtml";
    WebGrid grid = new WebGrid(rowsPerPage: Model.PageSize);
    grid.Bind(Model.Category,
              autoSortAndPage: false,
              rowCount: Model.TotalRows
    );
}
<h2>School Category</h2>



<div id="divmsg" style="color: green; font-weight: bold"></div>

<br />
<br />
@grid.GetHtml(
htmlAttributes: new { id = "grid" },
    fillEmptyRows: false,
    mode: WebGridPagerModes.All,
    firstText: "<< First",
    previousText: "< Prev",
    nextText: "Next >",
    lastText: "Last >>",
     columns: new[] {
         grid.Column(null,null,canSort:false, format: @<input type="hidden" name="IDHidden" value="@item.ID" />),

        grid.Column(header: "Category",format: @<span> <span id="spanName_@item.ID">@item.Category</span> @Html.TextBox("Category_"+(int)item.ID,(string)item.Category,new{@style="display:none"})</span>),


grid.Column(header: "Action",format:@<text> <a href="#" id="Edit_@item.ID" class="edit">Edit &nbsp;</a><a href="#" id="Update_@item.ID" style="display:none" class="update">Update &nbsp;</a><a href="#" id="Cancel_@item.ID" style="display:none" class="cancel">Cancel &nbsp;</a><a href="#" id="Delete_@item.ID" class="delete">Delete</a></text>)

})
<br />

<span class="glyphicon glyphicon-plus-sign"></span>
<a href="#" class="add">Add</a>




<style type="text/css">
    #grid {
        clear: both;
        width: 80%;
        margin: 0px;
        border: 1px solid #c7c5c7;
    }

        #grid thead, #grid tfoot td {
            text-align: left;
            font-weight: bold;
            height: 35px;
            color: #000;
            background-color: #d2d0d2;
            border-bottom: 1px solid #e2e2e2;
        }

        #grid td {
            padding: 4px 6px 0px 4px;
            vertical-align: top;
            background-color: #f5f5f5;
            border-bottom: 1px solid #e2e2e2;
        }

    input {
        border: 1px solid #e2e2e2;
        background: #fff;
        color: #333;
        font-size: 1.2em;
        margin: 2px 0 2px 0px;
        padding: 2px;
        width: 170px;
    }
</style>

<script src="~/Scripts/141jquery.js" type="text/javascript"></script>
<script type="text/javascript">

    $(".add").live("click", function() {

        var existrow = $('.save').length;

        if (existrow == 0) {
            var index = $("#grid tbody tr").length + 1;

            var Category = "Category_" + index;

            var Save = "Save_" + index;
            var Cancel = "Cancel_" + index;

            var tr = '<tr class="alternate-row"><td></td><td><span><input id="' + Category + '" type="text" class="ty" /></span></td>' +
                '<td> <a href="#" id="' + Save + '" class="save">Save&nbsp;&nbsp;</a><a href="#" id="' + Cancel + '"  class="icancel">Cancel</a></td>' +
                '</tr>';

            $("#grid tbody").append(tr);
        } else {

            alert('First Save your previous record !!');
        }

    });

    $(".icancel").live("click", function() {
        var flag = confirm('Are you sure to cancel');

        if (flag) {
            $(this).parents("tr").remove();
        }

    });

    $(".save").live("click", function() {
        var id = $("#grid tbody tr").length;
        var CateName = $("#Category_" + id).val();
        var index = $("#grid tbody tr").length + 1;

        if ($('.ty').val() === '') {
            alert('Text box can not be left blank');
            return false;
        }

        if (id != "") {

            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                @*url: '@Url.Action("SaveRecordCat", "Schools")'*@
                url: "/recognition/schools/SaveRecordCat",
                data: { "catee": CateName },
                dataType: "json",
                beforeSend: function() {},
                success: function(data) {
                    if (data.result == true) {

                        alert('Record has been saved successfully !!');

                        setTimeout(function() { window.location.replace("CreateCategory"); });
                    } else {
                        alert('Record already exist');

                    }

                }

            });
        }
    });

    $(".edit").live("click", function() {
        var str = $(this).attr("id").split("_");
        id = str[1];

        var CateName = "#Category_" + id;
        var spanName = "#spanName_" + id;

        $(CateName).show();
        $(spanName).hide();

        $(this).hide();
        $("#Update_" + id).show();
        $("#Cancel_" + id).show();
    });

    $(".cancel").live("click", function() {
        var str = $(this).attr("id").split("_");

        id = str[1];

        var CateName = "#Category_" + id;
        var spanName = "#spanName_" + id;


        $(CateName).hide();
        $(spanName).show();


        $(this).hide();
        $("#Update_" + id).hide();

        $("#Edit_" + id).show();
    });

    $(".update").live("click", function() {
        var str = $(this).attr("id").split("_");
        id = str[1];

        var CateName = $("#Category_" + id).val();
        var spanName = $("#spanName_" + id).val();


        if (id !== "") {
            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                @*url: '@Url.Action("UpdateRecordSchCate", "Schools")',*@
                url: "/recognition/schools/UpdateRecordSchCate",
                data: { "id": id, "catee": CateName },
                dataType: "json",
                beforeSend: function() {
                },
                success: function(data) {

                    if (data.result === true) {
                        $("#Update_" + id).hide();
                        $("#Cancel_" + id).hide();
                        $("#Edit_" + id).show();

                        var CateName = "#Category_" + id;
                        var spanName = "#spanName_" + id;


                        $(CateName).hide();
                        $(spanName).show();


                        $(spanName).text($(CateName).val());

                    } else {
                        alert('There is some error');
                    }
                }

            });
        }
    });

    $(".delete").live("click", function() {
        var str = $(this).attr("id").split("_");
        id = str[1];

        var flag = confirm('Are you sure to delete ??');
        if (id !== "" && flag) {
            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                @*url: '@Url.Action("DeleteRecordCategory", "Schools")',*@
                url: "/recognition/schools/DeleteRecordCategory",
                data: { "id": id },
                dataType: "json",
                beforeSend: function () { },
                success: function (data) {

                    if (data.result === true) {
                        $("#Update_" + id).parents("tr").remove();
                    }
                    else {
                        alert('There is some error');
                    }
                }

            });
        }
    });

</script>

SchoolRecognitionSystem/Views/Schools/DefineOption.cshtml
@{
    ViewBag.Title = "New School Operation";
    Layout = "~/Views/Shared/_LayoutUserHome.cshtml";

}
<div class="row">
    <div class="col-lg-11 col-md-11 col-sm-11 col-xs-11 mycustom-tab-container">
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 mycustom-tab-menu">
            @Html.Partial("_SubjectRecognition")
        </div>

        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 mycustom-tab" id="loadPagePanel">

        </div>


    </div>
</div>
@section scripts
{
    <script type="text/javascript">
        var defaultHtml = '<h2 class="ajax-loading-animation"><i class="fa fa-cog fa-spin"></i> Loading...</h2> ';
        $(function() {
            init();
         
        });

        function init() {
            $('a').css('cursor', 'pointer');

            //goto the last page if it exists
            var lastLink = localStorage.getItem('lastLink');
            if (lastLink === 'undefined') {
                return null;
            }
            if (lastLink) {
                if (lastLink === '#') {
                    e.preventDefault();
                } else {
                    $("#pageloading").show();
                    // $.blockUI();
                    $('#loadPagePanel').html(defaultHtml).show();
                    loadURL("/Schools/_DefineOption", $('#loadPagePanel'));

                    $("#pageloading").hide();
                }


            }
        }

        function loadURL(a, b) {
            // var host = document.location.host;
            var _host = window.location;
            _path = _host.toString().substring(0, _host.toString().indexOf('/Schools'));

            // alert("href"+ $(this).attr('href'));
            //Check if the site is running on development machine
            //if (host == "localhost:12027") {
            //    _path = location.protocol + '//' + location.host;
            //} else {
            //    if (a.indexOf(serverrootFolder) == -1 && a.indexOf(rootFolder) == -1) {
            //        _path = location.protocol + '//' + location.host + serverrootFolder;
            //    }
            //}
            ////Check if the url ends with /
            if (a.indexOf("/") == 0) {
                a = _path + a;
                //} else {
                //a = _path + a;
            }
            //alert("B4 ajax call >" + a);
            $.ajax({
                "type": "GET",
                "url": a,
                "cache": !0,
                "success": function(a) {
                    //alert(a);
                    b.css({ "opacity": "0.0" }).html(a).delay(50).animate({ "opacity": "1.0" }, 300), a = null, b = null
                },
                "error": function(c, d, e, f) {
                    //alert('Error' + a);
                    b.html('<h4 class="ajax-loading-error"><i class="fa fa-warning txt-color-orangeDark"></i> Error requesting <span class="txt-color-red">' + a + "</span>: " + c.status + ' <span style="text-transform: capitalize;">' + e + "</span></h4>")
                },
                "async": !0
            });
        }

        function openNext(url) {
            if (url == '#') {
                e.preventDefault();
            } else {
                $("#pageloading").show();
                // $.blockUI();
                $('#loadPagePanel').html(url).show();
                loadURL(url, $('#loadPagePanel'));

                $("#pageloading").hide();
            }
        }
        //Recognition
        function selectOnlyThis(id) {
     if (id === "TextBook") {
         document.location.href = "/Recognition/Schools/UpdateTextBook?schoolid=@Request.QueryString["schoolid"]";
     } else if (id === "Subject") {
         document.location.href = "/Recognition/Schools/UpdateSubject?schoolid=@Request.QueryString["schoolid"]";
     }
          
        }




    </script>
    @* ACTION PERFORM PARTIAL VIEW SCRIPTS *@
    <script type="text/javascript">



    </script>
}

SchoolRecognitionSystem/Views/Schools/DeleteTextBook.cshtml
@{
    ViewBag.Title = "DeleteTextBook";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<h2>DeleteTextBook</h2>

SchoolRecognitionSystem/Views/Schools/IndexDemo.cshtml
@model SchoolRecognitionSystem.Models.CountryModel           
@{
    ViewBag.Title = "Multi Select DropdownList Using jQuery in Asp.Net MVC";
}
<script src="~/Scripts/190jquery.min.js"></script>
<script src="~/Scripts/jquery.sumoselect.js"></script>
<link href="~/Content/dropdownliststyle.css" rel="stylesheet" />
 <script type="text/javascript">
     $(document).ready(function () {
         window.asd = $('.SlectBox').SumoSelect({ csvDispCount: 4 });
     });
    </script>
Country:
@Html.DropDownListFor(m => m.SelectedCountryId, new SelectList(Model.CountryList, "CountryName", "CountryName"), new {@multiple="multiple",@placeholder="Please select country", @class="SlectBox" })

SchoolRecognitionSystem/Views/Schools/RemoveSubject.cshtml
@{
    ViewBag.Title = "RemoveSubject";
    Layout = "~/Views/Shared/_LayoutUserHome.cshtml";
}

<h2>RemoveSubject</h2>

SchoolRecognitionSystem/Views/Schools/UpdateSchoolSubjectItems.cshtml
@using PagedList.Mvc;
@model   PagedList.IPagedList<SchoolRecognitionSystem.Models.SchoolEquipConfigViewModel>
@{
    ViewBag.Title = "EquipmentFacility";
    Layout = "~/Views/Shared/_LayoutUserHome.cshtml";
    //var totalGrades = Model.Sum(grade => int.Parse(grade.DigitValue));
}
<ol class="breadcrumb">
    <li><i class="glyphicon glyphicon-plane"></i></li>
    <li><a href="#">New School</a></li>
    <li class="active">Equipment Facility</li>
</ol>

<div class="row">
    <div class="col-lg-11 col-md-11 col-sm-11 col-xs-11 mycustom-tab-container">
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 mycustom-tab-menu">
            @Html.Partial("_TabPartial");
        </div>
       
    </div>
</div>

@section scripts{

  
}










@*===========================*@

SchoolRecognitionSystem/Views/Schools/_CreateSchoolProfileBreadcrumbPartial.cshtml
<li><a class="manage-special-links" href="@Url.Action("Create", "SchoolStaffs", new {sddc = Request.QueryString["sddc"]})" onclick="return canCreateManageStaff();">Manage staff</a></li>
             <li><a class="manage-special-links" href="@Url.Action("Subjects", "Schools", new {sddc = Request.QueryString["sddc"]})" onclick="return canCreateManageSubject();">Manage Subject</a></li>
                <li class="active"></li>